on: push
name: Ruff lint

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff

      - name: Lint Python files
        run: ruff check
